### ISSUE TITLE
Finalise strings for translation

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/ceno#128]
As a translator I want a tagged release containing the final version of all strings to be translated so that I can translate them without worrying about future changes

ACCEPTANCE CRITERIA

- [ ] I can see a tagged release in the master branch of the CENO repository that specifies the baseline for translation
- [ ] The README.md file and any other human-readable files in the distribution are updated to their final content (in English).
- [ ] I can see the same tagged release uploaded to the translation portal
- [ ] Updated versions of all strings are uploaded for translation
- [ ] Updated versions of all human-readable files are uploaded for translation
- [ ] I am aware of the languages to which the strings must be translated

**Comment by graphiclunarkid** [comment]
If there are strings or other text that we know will need to change later, let's make a list of those, so we can decide whether to delay translating those components.

**Comment by graphiclunarkid** [comment]
If we have a priority order for translation then let's write that out as a list too.

**Comment by redwire** [comment]
To review:

* [ ] README.md
* [ ] Error messages
    * [ ] Client
    * [ ] LCS
    * [ ] RS
* [ ] Error code spec (`doc/errorConditions.md`)
* [ ] CENO Protocol spec
* [ ] Firefox extension strings
* [ ] Chrome extension strings
* [ ] Bundle server strings
* [ ] BI and RR strings
* [ ] Reader strings
* [ ] Views
    * [ ] Please wait page
    * [ ] Error page

**Note** The product owner has previously said that we will not be translating strictly technical documents, such as build instructions.  We will assume technical people will have some English proficiency.

To do:

* [ ] Create a pad to discuss what text to write on the portal pages
* [ ] Add the text decided on to the CENO Client's translations file

**Comment by redwire** [comment]
This issue still needs attention from Marios, and is waiting on Dmitri for content for the "About CENO" page in the portal
