### ISSUE TITLE
Make CENO browsing immune to bridge failures

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#151]
As a user I want to establish my connection to CeNO once, rather than having to reestablish my connection to the network every time, so that bridge updates, failures or restarts don't prevent me from getting more websites.

ACCEPTANCE CRITERIA

 - [ ] I can launch CeNO, request some pages, turn off the bridge, turn it back on again and request another page. The last page I request (after reconnecting) is fetched as normal.

**Comment by vmon** [comment]
Hey, you haven't merged ChannelMaker.java. Could you please merge the whole branch? then I can work on my code. Thanks.
