### ISSUE TITLE
transport-node.js line 47 catches err ECONREFUSED; plugin-ceno gets no post requests on :3092

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#17]
transport-node.js log:

Error: connect ECONNREFUSED
at errnoException (net.js:904:11)
at Object.afterConnect as oncomplete

**Comment by misaakidis** [comment]
Related to joyent/node#5360
Dirty workaround 4cdf37c

**Comment by redwire** [comment]
What's the status on this? I'm confused about what is supposedly going on here.
Could you please provide more information about what you did to recreate this bug?

**Comment by misaakidis** [comment]
Can't replicate using the latest updates plus:
1) prefixing with http:// cacheServer and cenoClient in transport-node.js
2) replacing localhost with 127.0.0.1

Please don't close yet.

**Comment by redwire** [comment]
Alright. Please let me know when you have more information I can use to investigate this.

**Comment by misaakidis** [comment]
Can't replicate after 9e272e8
Looks like we'll have to reference modules including protocol ("http://127.0.0.1:port") in node.js in the future.
