### ISSUE TITLE
Localization of Error and "Bundle is being prepared" pages that is using the persistent portal locale

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#180]
As a user I would like all CENO pages to be translated in the locale I have set in the portal page.

ACCEPTANCE CRITERIA
  - [ ] User sets locale to something different than English (EN)
  - [ ] User makes a request for a URL
  - [ ] The "Bundle is being prepared" page is using the same locale with the one selected in the portal
  - [ ] User requests for an invalid URL, the error page is also translated

**Comment by misaakidis** [comment]
Implementation instructions:
* Make the portal locale global (accessible in client.go)
* In client.go, instead of using T, _ := i18n.Tfunc(os.Getenv("CENOLANG"), "en-us") use the portal locale
* Make sure that the language codes match (eg "en-us" vs "en")

**Comment by vmon** [comment]
https://github.com/equalitie/ceno/tree/180-propagate-portal-local-accross-client
