### ISSUE TITLE
Processes stored from previous executions of ceno-node "interfere" with new ones for the same url.

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#20]
Requests get back as response the corresponding pid of the previous execution and no new process is started to get the bundle. In client side, every time the page refreshes, the please wait page is shown.

Proposed solution: clear db/processes.json at ceno-node initialization.

**Comment by redwire** [comment]
This was fixed in (the poorly-named) https://github.com/equalitie/ceno/commit/6fac7ff53cc3d5280568c519dc6266a0a554c05f
