### ISSUE TITLE
Update or remove out-of-date Github documentation

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#239]
The Github wiki and repository have a bunch of outdated documentation - however the main README.md file points to the wiki. We should delete the reference and the github wiki and any out of date documentation in the repository.

Better documentation is on the censorship.no website. We should update content from the wiki and move it over to the website.

**Comment by florianap** [comment]
The wiki documentation doesn't look so out of date to me. I'll update the README and look for obsolete documentation while I wait for details on what needs to be updated in the wiki.

**Comment by florianap** [comment]
I've updated the README and INSTALL instruction. I've deleted wiki pages and updated and renamed them in the repo, also updating link in README.
I've kept the wiki home. If everybody is ok with it, I would add that content to the top of the README too.
