### ISSUE TITLE
Long lookup requests from browsers time out

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#27]
Lookup requests that exceed browser's corresponding network variable timeout before the "Please Wait" page is shown. The page will not auto-refresh and users will not get a result unless they manually refresh the page. Meanwhile, the background transport/caching process is continuing on normally.
This can be fixed:

* By configuring the browser appropriately (in Firefox adjusting network.http.response.timeout)
  * We have to add this in the deployment steps for the demo
* cenotransport returns a "Please Wait - Lookup in progress" page that auto-refreshes.
* When transport plugin is ready, it will handle this issue.

**Comment by redwire** [comment]
This is effectively solved by the implementation of the new protocol.
