### ISSUE TITLE
Ceno Inforgraphics

### ISSUE THREAD

**Issue by kromcuich** [equalitie/ceno#29]
![ceno_infographic_02](https://cloud.githubusercontent.com/assets/4204594/6418344/7164c042-be82-11e4-84bb-2dd12f2d86cc.jpg)

![ceno_infographic_01](https://cloud.githubusercontent.com/assets/4204594/6418347/78fbfe88-be82-11e4-853c-9863030b11c4.jpg)

**Comment by redwire** [comment]
I've updated the second infographic for the site in https://github.com/equalitie/censorship-no-site/commit/d93f6247fbbff6671d5acd4ca27872dc69098866
This means you can have someone (nosmo?) pull the changes so the update is reflected on https://censorship.no.

I'll close this now, assuming everything's good now that these two, fully up-to-date infographics are in the site's repository.
