### ISSUE TITLE
message-to-edge plugin discussion

### ISSUE THREAD

**Issue by billdoran** [equalitie/ceno#30]
A: Direct node to node message exchange (as proposed at
https://emu.freenetproject.org/pipermail/devl/2015-February/037988.html
). 
Plus+ very fast
Minus- forces clients to add bridges as friends inevitably exposing
their IP and the fact that they are using CeNo (and the URLs they are
requesting to be cached); also we'll have to find a way for announcing
bridges' nodes descriptors. Authorities can block the IP of the bridge
and access to CeNo.

B: freemail/FLIP strategy of using WoT identities.
Plus+ we ship CeNo client-plugin with the identity of the bridge and
it's public key hardcoded. Client and bridge do not directly exchange
packets and not need not know each other's IP. It is much more difficult
for authorities to block access to the bridge, since its IP is not
announced and acts as a normal node.
Minus- requests to URLs that have not been cached before will take extra
time to complete. Sometimes, messages to identities do not arrive at
all. More complex to implement. Requires bootstrapping with the users
creating identities, solving captchas and waiting for a few hours.
Authorities can circulate CeNo jars with an identity they own and reply
with content that somehow exposes the nodes (again, we have to apply
filters/rewrite HTML CSS and JS parts before caching and after
fetching).

**Comment by redwire** [comment]
In our last meeting, we agreed that option A is infeasible.  Since option B is the only reasonable way to do this, shall we either create a new task to document and build this for @misaakidis or else just close this task and leave it?
