### ISSUE TITLE
Drop Phantom for manual resource management

### ISSUE THREAD

**Issue by redwire** [equalitie/ceno#4]
Because I was having trouble with PhantomJS giving `AssertionError`s previously, I took some time to try to isolate the problem in my own branch, where I bypassed the bundler's functionality and had it simply use PhantomJS to forward requested pages' contents onto the requester.  The most recent two commits in [my branch](https://github.com/redwire/ceno/commits/simplebundle) show how I did this.

In my first commit I succeeded in having requests forwarded through the bundler and ended up in the same state I had things in before doing this, where pages would be simply returned back to the browser but fetching resources wouldn't work right and PhantomJS would crash.  I was able to identify the fact that PhantomJS was crashing because it was being exited prematurely.

After blocking requests for individual resources coming from the browser (which was making requests that duplicated the ones Phantom itself would be making since the browser would render the page before receiving bundled resources), I was able to push basic pages through the bundler without resources. @billdoran was able to confirm this worked.

Because I observed this behavior, I had the following idea to make everything much simpler and more extensible for the future. What I propose we do is drop PhantomJS in favor of manually managing resources. The process of bundling a page would then work like this:

1. A request for a page (e.g. http://duckduckgo.com) is forwarded to the bundler by the cache proxy (i.e. a cached bundle does not yet exist).
2. The bundler makes a request for the requested page itself (using a library like [request.js](https://github.com/request/request) or [superagent](https://github.com/visionmedia/superagent)).
3. The bundler then enumerates a collection of special identifiers for elements containing resources we want to bundle.
4. It then parses the document using a library like [Cheerio](https://github.com/cheeriojs/cheerio) or [jsdom](https://github.com/tmpvar/jsdom) to build a collection of resource URLs.
5. It then requests resources in whatever order makes sense as in step 2.
6. Documents containing content like CSS or JS can be parsed for URLs either with simple regex or filetype-specific parsers to recursively bundle the content.
7. The bundler replaces URLs for resources with the data URIs it has built using the parsing library chosen above instead of naive text replacement.
8. Finally, the bundled page is served back to the requester.

This is a rather detailed explanation and might seem like a bit of extra work, but Bill and I agree this would be a lot more simple than trying to keep track of the context resources are being referred to in as we currently have to using PhantomJS.  This approach would give us direct control over the order in which resources are fetched and how they are handled.  It also means we no longer need to worry about how we handle PhantomJS instances (which was causing errors previously), and means we will be able to apply the same solution to implementations of the bundler in other languages (e.g. Python).  Of course, it also means it will be a lot easier to grow the software to handle more use cases since we can describe resources that need to be handled explicitly with CSS selectors and associated handler functions, which would also make the caching process more explicit, and that further means it would be a great deal easier to modularize and test.

I figure this change could be implemented quite quickly.

If anyone has any questions, I'll be glad to answer them.

**Comment by nosmo** [comment]
:+1: 

I like the sound of this, especially given that it reduces any of the existing IPC problems and hopefully can get us more meaningful information out of failed resource loads etc. 

I'm vaguely concerned about the amount of edge cases involved ensuring we get all resources, but as it stands those very same concerns exist for PhantomJS, just in a different manner. Being able to do easy configuration of things like header manipulation, SSL configuration etc from a high level via whatever interface is developed would be extremely useful - PhantomJS has these things, it's just uncertain whether the node interface to it ever even passes the options.
