### ISSUE TITLE
Client cannot handle HTTPS requests

### ISSUE THREAD

**Issue by redwire** [equalitie/ceno#43]
When using CeNo client as a standard HTTP proxy, requests to any site protected by SSL/TLS return the following error (using CURL):

    curl: (56) Received HTTP code 404 from proxy after CONNECT

Firefox simply reports that it cannot find the server hosting the website.

**Comment by misaakidis** [comment]
Can replicate with Chromium.
chromium-browser --incognito --proxy-server="http=127.0.0.1:3090"

**Comment by redwire** [comment]
Working on this issue in https://github.com/equalitie/ceno/tree/handletls.  Until we hear something from Hugh, I'm going to go ahead with trying to make a Firefox extension to intercept requests.

**Comment by Manouchehri** [comment]
@redwire If you intercept an HTTPS request and forward it via HTTP to the node, how will the node be able to tell if the user is trying to access a site that only listens for HTTPS (not common, but still), or even worse, forwards `http://example.org/path/to/file/index.html` straight to `https://example.org/`?

**Comment by misaakidis** [comment]
@Manouchehri in the caching side, the bridge will try to use HTTPS when possible -we'll probably use the HTTPS Everywhere rules- over tor and insert the content (the HTML page, images, CSS etc.) in Freenet.

What we are planning to do with HTTPS requests in the client side, is to have them handled by a browser plugin. When the user hits the Go button, the plugin will listen to the event, stop the browser from making any GET requests, and send the URL to the CENO Client proxy (CC) agent. The CC will then query Local Cache Server (LCS) agent to make a lookup for a bundle for that URL in the distributed cache.

Once the bundle for the URL is retrieved via Freenet, LCS will serve the HTML via HTTP to CC in localhost. You can be sure that the content has not been altered and was inserted by the insertion authority you trust (more info here https://wiki.freenetproject.org/Signed_Subspace_Key). Therefore HTTPS in the client side is not a necessity.

More about agents and the CENO protocol here: https://github.com/equalitie/ceno/blob/master/doc/CeNoProtocol.md

**Comment by Manouchehri** [comment]
Not sure if you already have your eye on this, [there's somebody who's started a HTTPS Everywhere library](https://github.com/grindhold/libhttpseverywhere). I think it's functional, might save you some time.

Definitely, I'm not worried about HTTP being served on the node <-> browser side, I was more commenting on the bridge side (don't go hammering servers on port 80 when they're only listening on 443 ;P ).

**Comment by redwire** [comment]
This issue is being handled with ceno-chrome
