### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by Manouchehri** [equalitie/ceno#52]
At the moment I don't see any information regarding running CENOBox on Windows. In theory everything seems to be cross-platform, except all/most of the build scripts.

I don't run Windows myself, but that's probably going to be the most popular end-user platform as usual. I'd also look into testing against Windows XP, it's still extremely popular in a lot of countries (e.g., China and Russia).

**Comment by redwire** [comment]
A distribution for Windows is a long ways off.
We are currently only really targeting Linux users as our beta release approaches, and we have a very specific audience on top of that- namely, Freenet users and other relatively savvy individuals.
