### ISSUE TITLE
Make CeNo-node to listen on port 3093 for bundling request

### ISSUE THREAD

**Issue by vmon** [equalitie/ceno#7]
CeNo-node should listen to on port 3093. When it receive an http request from this port, bundles the request and reply the bundle as the response.

**Comment by redwire** [comment]
How do we want to be making requests for pages?
Is it still alright to have CeNo-node get the url to fetch from the queries? Then, requests to the CeNo-node server would look like:

    GET <ceno-node-ip>:3093/?url=<URL>

So that, for example if fetching google.com across localhost, we'd send a request to

    localhost:3090/?url=https://google.com/
