### ISSUE TITLE
If feeds.json has new feeds and LCS has not downloaded them yet, users get a fatal error page

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#76]
* User downloads CENO with feeds.json v0
* LCS fetches in the background feeds.json v1
* Once feeds.json v1 is retrieved, LCS subscribes to the USKs of the feeds
* In the meantime a user clicks on a feed for which lookup is not yet complete
* CC gets a {complete: false} response from LCS and tries to serve a json from the disk. Such a json does not exist, since it wasn't available when CENOBox was created.
* User sees a fatal error page

**Comment by misaakidis** [comment]
Error page includes the following message:

We couldn't prepare your bundle!

You asked for http://localhost:3090/cenosite/aHR0cDovL21pc2Fha2lkaXMuZ2l0aHViLmlvL2F0b20ueG1s

Here's the error we got: open json-files/aHR0cDovL21pc2Fha2lkaXMuZ2l0aHViLmlvL2F0b20ueG1s.json: no such file or directory

What you can do

No article listing file could be found for the feed you tried to access.

**Comment by graphiclunarkid** [comment]
I think this is quite likely to happen to new users, and it's a poor UX if it does happen. @redwire and I discussed the problem during sprint planning. We thought the best solution would be to prevent the LCS from serving new feeds.json files until all the corresponding article-list files are available, thus preventing this situation from occurring.
