### ISSUE TITLE
Insert new RSS articles into Freenet automatically

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/ceno#78]
As a CENO portal user I want new articles on RSS feeds to which bridge nodes subscribe to be inserted automatically so that I can read them at the earliest available opportunity.

ACCEPTANCE CRITERIA

- [ ] When a new article is published on an RSS feed subscribed to by a bridge node, when I next open my client, the new article is listed automatically.

**Comment by redwire** [comment]
This is part is related to PR #107
