### ISSUE TITLE
Handle empty feeds.json and articles lists

### ISSUE THREAD

**Issue by misaakidis** [equalitie/ceno#80]
Make sure empty or malformed feeds.json and articles lists files are not breaking the CENO Client agent.

**Comment by redwire** [comment]
To check:

1. Handling errors reading JSON files
2. Handling errors decoding JSON files
3. If the "feeds" field in `feeds.json` is empty or "articles" in an article JSON file is empty, the portal page just displays no feeds/articles instead of producing an error

**Comment by redwire** [comment]
Cases 1 and 2 are handled by CreatePortalPage

```go
moduleData, feedsErr := initModuleWithFeeds()
	if feedsErr != nil {
		// We could end up with a decode error here, but it's not quite practical to ditinguish.
		HandleCCError(ERR_NO_FEEDS_FILE, feedsErr.Error(), ErrorState{
			"responseWriter": w,
			"request":        r,
		})
		return
	}
```

and CreateArticlePage

```go
moduleData, articlesErr := initModuleWithArticles(feedUrl)
	if articlesErr != nil {
		HandleCCError(ERR_NO_ARTICLES_FILE, articlesErr.Error(), ErrorState{
			"responseWriter": w,
			"request":        r,
		})
		return
	}
```

**Comment by redwire** [comment]
Checked and verified that the last case is a non-issue. Indeed, a page that lists either no feeds or no articles is served with no problem.
