### ISSUE TITLE
Update code comments

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/ceno#84]
As an auditor I want the code to be commented correctly and in appropriate detail so that I can understand how it works

ACCEPTANCE CRITERIA

- [ ] Code comments reviewed by Marios
- [ ] Code comments reviewed by Zack

**Comment by redwire** [comment]
To visit:

* [ ] Client
* [ ] Local Cache Server
* [ ] Bundle Server
* [ ] RSS Reader

Others?

**Comment by redwire** [comment]
Handing this over to Marios for completion before we both review.
