### ISSUE TITLE
Review agents adherance to published protocol

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/ceno#85]
As an auditor I want a list of known ways in which the agents deviate from the protocol so that I can review the code more efficiently.

ACCEPTANCE CRITERIA

- [ ] I can read a list of github issues that document how the agents need to change in order to conform to the protocol, if any
- [ ] I can read a list of proposed protocol changes to bring it into line with our implementation decisions, if any
- [ ] The issues are summarised in the release notes for the next release

**Comment by redwire** [comment]
To review:

* [ ] CC conforms to protocol spec
* [ ] LCS conforms to protocol spec
* [ ] RS conforms to protocol spec
* [ ] RR conforms to protocol spec
* [ ] BS conforms to protocol spec
* [ ] BI conforms to protocol spec
* [ ] CC only outputs errors in errorSpecification
* [ ] LCS only outputs errors in errorSpecification
* [ ] RS only outputs errors in errorSpecification
* [ ] RR only outputs errors in errorSpecification
* [ ] BS only outputs errors in errorSpecification
* [ ] BI only outputs errors in errorSpecification
* [ ] All the example commands in the readerAPI doc work as expected

**Comment by redwire** [comment]
Finished checking the CC and BS against the protocol spec.
I created the `Protocol Adherence` tag to capture issues we pick up in our investigations here.

**Comment by redwire** [comment]
I'm done my part of this. Passing the rest off to Marios until we're ready for review.
